- lib/scout_apm/instruments/samplers/memory.ex
- lib/scout_apm/internal/metric.ex
- lib/scout_apm/store.ex
This reports the total memory used with every reporting period. A side result: we'll get some metrics even if an app isn't handling throughput. 
Without that, an app can appear as not reporting.
> Adds a memory sampler

- lib/scout_apm/instruments/ecto_logger.ex
- lib/scout_apm/internal/layer.ex
- lib/scout_apm/tracing.ex
- lib/scout_apm/tracked_request.ex
IE: 
track("HTTP", "get", 300, :milliseconds, desc: "HTTP GET http://api.github.com/")
Also adjusted `TrackedRequest.track_layer` to account for the new `fields` param.
> Ability to record a description via `Tracing.track`

- lib/scout_apm/application.ex
- lib/scout_apm/application_load_notification.ex
- lib/scout_apm/payload/app_server_load.ex
Sends basic info about the agent and its environment at boot time of an application.
This is mostly useful for updating the ui faster during onboarding and debugging of agent issues.
> App server load

- lib/scout_apm/config/defaults.ex
- lib/scout_apm/devtrace/plug.ex
DevTrace assets were trying to load thru the ingestion pipeline, which is incorrect. This adds a `direct_host` option and loads the assets from there.
It's likely only to be used in development.
This fixes the missing asset mentioned in #17.
> Adding a `direct_host` option to fix loading DevTrace assets

- lib/scout_apm/collector.ex
- lib/scout_apm/instruments/eex_engine.ex
- lib/scout_apm/internal/layer.ex
- lib/scout_apm/scope_stack.ex
- lib/scout_apm/tracing.ex
- lib/scout_apm/tracked_request.ex
Enables nesting of layers inside of traces.
For instance:
Currently APM only supports a single layer of nesting, so view partials inside of view partials will get flattened out. This will likely be extended to deeper nesting in the future.
> Nested scopes

- lib/scout_apm/reporter.ex
- lib/scout_apm/store_reporting_period.ex
Previously we'd log the following on the per-minute reporting cycles:
```
15:20:07.638 application=scout_apm [info] Reporting: Payload created with data from 7 requests.
15:20:07.644 application=scout_apm [info] Reporting ScoutAPM Payload to http://localhost:3000/apps/checkin.scout?key=[KEY]&name=[APP NAME]
15:20:07.947 application=scout_apm [info] Reporting ScoutAPM Payload Succeeded. Status: 200
```
Now, nothing is logged when the payload is created and reported without error.
Closes #20.
> Less info-level logging on the per-minute reporting cycles

- lib/scout_apm/collector.ex
- lib/scout_apm/devtrace/store.ex
- lib/scout_apm/internal/context.ex
- lib/scout_apm/internal/job_record.ex
- lib/scout_apm/internal/job_trace.ex
- lib/scout_apm/internal/web_trace.ex
- lib/scout_apm/metric_set.ex
- lib/scout_apm/payload.ex
- lib/scout_apm/payload/jobs.ex
- lib/scout_apm/payload/new_metrics.ex
- lib/scout_apm/payload/slow_jobs.ex
- lib/scout_apm/payload/slow_transaction.ex
- lib/scout_apm/store.ex
- lib/scout_apm/store_reporting_period.ex
- lib/scout_apm/tracing.ex
- lib/scout_apm/tracked_request.ex
- lib/scout_apm/utils.ex
- test/scout_apm/internal/job_record_test.exs
- test/scout_apm/metric_set_test.exs
- test/scout_apm/payload/jobs_test.exs
- test/scout_apm/tracked_request_test.exs
This is an initial implementation of background job monitoring and tracing.
There's no automated instrumentation of any specific workers yet, to use this,
you'll need to wrap your job code in a tracing function:
```
def perform do
ScoutApm.Tracing.track_job("MyJob", fn ->
end)
end
```
> Background Job Metrics & Traces

- lib/scout_apm/agent_note.ex
- lib/scout_apm/application.ex
- lib/scout_apm/application_load_notification.ex
- lib/scout_apm/config.ex
- lib/scout_apm/context.ex
- lib/scout_apm/devtrace/plug.ex
- lib/scout_apm/devtrace/store.ex
- lib/scout_apm/instruments/eex_engine.ex
- lib/scout_apm/internal/job_trace.ex
- lib/scout_apm/internal/web_trace.ex
- lib/scout_apm/logger.ex
- lib/scout_apm/plugs/controller_timer.ex
- lib/scout_apm/reporter.ex
- lib/scout_apm/store.ex
- lib/scout_apm/store_reporting_period.ex
- lib/scout_apm/tracing.ex
- lib/scout_apm/tracked_request.ex
- lib/scout_apm/watcher.ex
Allows further customization of the log level from the agent.
2 Major features:
- A log level distinct from the application's level (app is at info, but
scout is at warn). This is mostly useful for the console logger, since
the file logger can already be setup in a way similar to this.
- Disables logging entirely when ScoutAPM agent is not enabled.
> Implement a passthrough ScoutApm.Logger module

- lib/scout_apm/tracing.ex
- lib/scout_apm/tracing/annotations.ex
- test/scout_apm/tracing_test.exs
Previously, we attempted to mark the same function overridable several
times, which raised a compile-time error.  This adds a check so we don't
do it more than once per function.
> Fix Multiple definitions tracing

- lib/scout_apm/config.ex
- lib/scout_apm/config/application.ex
- lib/scout_apm/config/env.ex
- test/scout_apm/config_test.exs
Split out the two approaches to ENV vars
In mix, you can set your own ENV var to look up. This matches with how
other libraries in the elixir ecosystem do environment variables.
```
config :scout_apm,
key: {:system, "APM_API_KEY"}
```
To match our Ruby agent, and make configuration easier on Heroku and
similar platforms, we also have a set of automatically derived
configurations.  For any config option (`key`, `log_level`), upper case
it, and prepend "SCOUT_", and that value will be loaded.
SCOUT_LOG_LEVEL
SCOUT_KEY
SCOUT_MONITOR
> Load configuration variables from ENV

- lib/scout_apm/config.ex
- lib/scout_apm/config/env.ex
- test/scout_apm/config_test.exs
This allows to set `:key` via environmental variables on platforms such as Heroku without the need to rebuild the application.
Here is how to use it:
```elixir
config :scout_apm,
key: {:system, "SCOUT_API_KEY"}
```
> Add support loading config from ENV

- lib/scout_apm/agent_note.ex
- lib/scout_apm/application.ex
- lib/scout_apm/application_load_notification.ex
- lib/scout_apm/config.ex
- lib/scout_apm/internal/job_trace.ex
- lib/scout_apm/internal/web_trace.ex
- lib/scout_apm/logger.ex
- lib/scout_apm/plugs/controller_timer.ex
- lib/scout_apm/reporter.ex
- lib/scout_apm/store.ex
- lib/scout_apm/store_reporting_period.ex
- lib/scout_apm/tracing.ex
- lib/scout_apm/watcher.ex
- mix.exs
- test/scout_apm/config_test.exs
- test/scout_apm/internal/job_record_test.exs
- test/scout_apm/logger_test.exs
- test/scout_apm/metric_set_test.exs
Closes #43 
This also replaces the current `ScoutApm.Logger` GenServer with a direct module that can depend on the `Elixir.Logger` backpressure mechanisms. Like the GenServer version, this Logger will not have the log calls compiled out.
> Silence logging when no key present

- lib/scout_apm/application.ex
This fixes an error that pops up when testing apps using this library that happens because `ScoutApm.ApplicationLoadNotification` tries to access the ets table created by the cache before the table is set up.
```
[error] GenServer ScoutApm.ApplicationLoadNotification terminating
** (ArgumentError) argument error
(stdlib) :ets.lookup(:scout_cache, :hostname)
(scout_apm) lib/scout_apm/cache.ex:15: ScoutApm.Cache.hostname/0
(scout_apm) lib/scout_apm/payload/app_server_load.ex:16: ScoutApm.Payload.AppServerLoad.new/0
(scout_apm) lib/scout_apm/application_load_notification.ex:33: ScoutApm.ApplicationLoadNotification.handle_cast/2
(stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
(stdlib) gen_server.erl:686: :gen_server.handle_msg/6
(stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 …
```
> setup cache before starting supervisor

- lib/scout_apm/cache.ex
- lib/scout_apm/internal/job_trace.ex
- lib/scout_apm/internal/web_trace.ex
- lib/scout_apm/payload/app_server_load.ex
- lib/scout_apm/payload/slow_jobs.ex
- lib/scout_apm/payload/slow_transaction.ex
- test/scout_apm/cache_test.exs
* Adds detection of the running Git SHA if it can be detected. Currently this looks
at Heroku's env var, or a customer-set revision_sha setting (same as any other config).
* Connects the detected SHA to the appropriate payloads to trigger server-side
logic of deploy tracking.
* Connects the detected SHA to individual traces, they it can be found in the
Context pane of the trace view in the Web UI
> Add Deploy Detection & Tracking

- lib/scout_apm/instruments/ecto_logger.ex
- lib/scout_apm/instruments/ecto_telemetry.ex
- mix.exs
- mix.lock
- test/scout_apm/instruments_ecto_logger_test.exs
> telemetry implementation for Ecto 3

- lib/scout_apm/instruments/ecto_logger.ex
- lib/scout_apm/internal/layer.ex
- lib/scout_apm/payload/metadata.ex
- test/scout_apm/payload/metadata_test.exs
Ran the tests with 1.8.0-rc.1 and got some deprecation warnings, this should fix them.
> rename *seconds to *second, move System.cwd to File.cwd to fix all deprecations on 1.8.0

- lib/scout_apm/store_reporting_period.ex
Got this deprecation warning on Elixir 1.8.1
> fix deprecation warning on NaiveDateTime.diff/3 use singular :second

- lib/scout_apm/instruments/ecto_telemetry.ex
- mix.exs
- mix.lock
ecto_sql bumped the version of telemetry that included some breaking changes:
https://github.com/elixir-ecto/ecto_sql/blob/master/CHANGELOG.md#enhancements-2
https://github.com/beam-telemetry/telemetry/blob/master/CHANGELOG.md#030
There's also a `0.4.0` out, but doesn't look like Ecto has a release that includes it (yet)
> upgrade telemetry

- lib/scout_apm/instruments/ecto_telemetry.ex
This allows an arbitrary nesting of the module without breaking the
handle_event pattern match. Just ignores the data since we weren't using
it anyway.
We can't simply change the naming of the query_event list because the Ecto
side emits events under the exact name. Search on `telemetry_prefix` in docs
if you want to see more
Fixes #76
> Don't rely on prefix of Telemetry when pattern matching the handler

- lib/scout_apm/config/defaults.ex
(from CA's changelog)
[1.2.6] 2019-12-03
Fixed:
* Use SQL derived names in SpanTraces (#97)
[1.2.5] 2019-12-02
Added:
* Autoclose running spans when request finishes (#93)
* Rate Limit AppServerLoad metadata (#94)
* Add `language_version` key to AppServerLoad metadata (#95)
Fixed:
* Prevent errors if AppServerLoad metadata is not set (#92)
> Update CoreAgent version to 1.2.6, with several bug fixes

- lib/scout_apm/config/defaults.ex
- lib/scout_apm/instrumentation.ex
- lib/scout_apm/instruments/eex_engine.ex
- lib/scout_apm/instruments/exs_engine.ex
- lib/scout_apm/instruments/slime_engine.ex
- lib/scout_apm/plugs/controller_timer.ex
- test/scout_apm/plugs/controller_timer_test.exs
Currently, the way the library is setup controller instrumentation
reports controller names sans the app name. As an example, in a standard
Phoenix app if I have a controller called `ExampleApp.SessionController`
then it will be reported under `SessionController#action_name`. This is
very convenient for apps that only have one phoenix app since it reduces
verbosity.
However, we're running Scout in an umbrella app that has multiple
Phoenix apps underneath it. So in our setup we might have something that
looks like this: `ExampleApp1.SessionController` and
`ExampleApp2.SessionController`. With the current implementation,
instrumentation of both controllers results in metrics being sent to the
same `SessionController#action_name` which is undesirable because we
would like them to be reported …
> Add option to control whether the app name is trimmed from controllers

- lib/scout_apm/commands.ex
- lib/scout_apm/core/agent_manager.ex
- Use the correct function signature for `start_link` in `ScoutApm.Core.AgentManager`.
- Fix typo in `commands.ex`.
> Add missing param in start_link definition
